version: "3"
services:
  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - db-volume:/data/db
    ports:
      - "27017:27017"
  dbseed:
    build:
      context: ./DATABASE
    depends_on:
      - mongo
    command: ["sh", "-c", "until nc -z mongo 27017; do sleep 1; done; node index.js"]
  server:
    build:
      context: ./BACKEND
    environment:
      - MONGO_URI=mongodb://mongo:27017/mongo
    ports:
      - "4000:4000"
    depends_on:
      - dbseed
    volumes:
      - ./BACKEND:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  frontend:
    build:
      context: ./FRONTEND/react-pbtech-redesign
    ports:
      - "3000:80"
    depends_on:
      - server
volumes:
  db-volume: